"""empty message

Revision ID: 302c14ad6bc1
Revises: d3855a0e976a
Create Date: 2018-10-13 09:29:16.026050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302c14ad6bc1'
down_revision = 'd3855a0e976a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###
